# Generated by Django 4.0.2 on 2022-02-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150)),
                ('other_name', models.CharField(max_length=200)),
                ('Date_of_Birth', models.DateField()),
                ('LGA', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('previous_school', models.CharField(max_length=500)),
            ],
        ),
    ]
